#!/usr/bin/env python3
"""Regenerate tests/pressure/INDEX.md from map.tsv + proves.tsv.
Run after any map/proves edit; scripts/lint.py verifies the result is in sync."""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = os.path.join(ROOT, 'tests', 'pressure')

rows = [l.split('\t') for l in open(os.path.join(P, 'map.tsv')).read().splitlines() if l.strip()]
proves = {}
for l in open(os.path.join(P, 'proves.tsv')).read().splitlines():
    if l.strip():
        k, _, v = l.partition('\t')
        proves[k] = v

missing = [r[0] for r in rows if r[0] not in proves]
extra = [k for k in proves if k not in {r[0] for r in rows}]
if missing or extra:
    print(f"proves.tsv out of sync: missing={missing} extra={extra}")
    sys.exit(1)

out = [
    "# Evidence index — what each pressure scenario proves",
    "",
    "GENERATED by scripts/gen-index.py from map.tsv + proves.tsv — edit those, not this file.",
    "",
    "The family's rules were not written from taste: each scenario records a real baseline failure "
    "(a fresh session WITHOUT the skill choosing the wrong action under pressure) that a rule was "
    "then written to close. Scenario text: `scenarios/<name>.md`; run history and scoring: "
    "`../README.md` (append-only journal). The harness now runs only to baseline NEW rules "
    "(policy: journal 0.6.3 NOTE).",
    "",
    "| Scenario | Tier | What it proves | Primary surface |",
    "|---|---|---|---|",
]
for r in rows:
    name, model, files = r[0], r[1], r[2:]
    surface = files[0] + (f" (+{len(files)-1})" if len(files) > 1 else "")
    out.append(f"| `{name}` | {model} | {proves[name]} | {surface} |")
out += ["", f"{len(rows)} scenarios total. Full file lists: `map.tsv`."]
open(os.path.join(P, 'INDEX.md'), 'w').write('\n'.join(out) + '\n')
print(f"INDEX.md regenerated ({len(rows)} scenarios)")
